# Combine individual output into one file
Run the code in terminal.

In [1]:
import os
import pandas as pd

# 1. Combine all individuals wirth valid result file

Run this in terminal

In [ ]:
# def split_one_result(df:pd.DataFrame):
#     '''
#     Split one output file by HLA gene, and return reformatted string for each gene.
#     Params:
#     - df: a dataframe of a single result from Kourami run
#     Return:
#     - dict_output_strs: a dictionary of reforamtted output line for each gene, as gene:line.
#     '''
#     df['HLA_gene'] = df[0].apply(lambda x: x.split('*')[0])
#     dict_output_strs = dict()

#     for gene, df_single_gene in df.groupby('HLA_gene'):
#         output_str = ''
#         for col in df_single_gene.columns[:-1]: # Skip the last col as it is HLA_gene
#             output_str += '\t'.join(df_single_gene[col]) + '\t'
#         dict_output_strs[gene] = output_str.strip()+'\n'
#     return dict_output_strs


# def combine_individual_results(result_path:str='/DC3/AGD250k_HLA_typing/individual_hla_results/kourami_run_3.24',
#                                hla_genes:list=['A', 'B', 'C', 'DQA1', 'DQB1', 'DRB1'],
#                                output_prefix:str='./AGD250k.kourami.imgt_v3.24') -> pd.DataFrame:
#     '''
#     Params:
#     - result_path: a directory to kourami results. The funciton expects each individual to have a folder with all files stored.
#                    The function will look for result files as <result_path>/<sample_id>/<sample_id>_out.result.
#     - hla_genes: the HLA genes to call. The default 6 are A, B, C, DQA1, DQB1,and DRB1.
#                  Kourami can output additional HAL genes with flag `-a`,
#                  but it may consume too much resource so I skip other genes for IMGT version >v3.24 (the default version).
#     Return:
#     - Output combined results to files. One HLA gene per file for all samples. The 
#     '''
#     c_total, c_completed = 0, 0
#     hla_genes = set(hla_genes) # In case there are duplicates
#     dict_output_fhs = {}
#     header = 'grid\tallele1\tallele2\t#BasesMatched_a1\t#BasesMatched_a2\tIdentity_a1\tIdentity_a2\tassembled_length_a1\tassembled_length_a2\tIMGT_DB_allele_length_a1\tIMGT_DB_allele_length_a2\tcombined_bottleneck_weight_a1\tcombined_bottleneck_weight_a2\tbottleneck_weight_path1_a1\tbottleneck_weight_path1_a2\tbottleneck_weight_path2_a1\tbottleneck_weight_path2_a2\n'
#     for gene in hla_genes:
#         dict_output_fhs[gene] = open(f'{output_prefix}.HLA_{gene}.txt', 'w')
#         dict_output_fhs[gene].write(header)
        
#     for sample_id in os.listdir(result_path):
#         c_total += 1
#         result_file = f'{result_path}/{sample_id}/{sample_id}_out.result'
#         df_result = pd.read_csv(result_file, sep='\t', dtype=str, header=None)
#         # Get result for each individual and write to output
#         dict_strs = split_one_result(df_result)
#         for gene in hla_genes:
#             try:
#                 dict_output_fhs[gene].write(sample_id + '\t' + dict_strs[gene])
#                 c_completed += 1
#             except:
#                 print(f'# Error: HLA gene {gene} not found in result file for sample {sample_id}')

#         if c_total%50 == 0:
#             print(f'\rProcessed (completed/total): {c_completed}/{c_total}', end='', flush=True)


#     for gene in hla_genes:
#         dict_output_fhs[gene].close()

In [21]:
result_path = '/data100t1/home/wanying/BioVU/20260305_AGD_250k_HLA_typing/output/kourami_output_examples'
combine_individual_results(result_path=result_path,
                           hla_genes=['A', 'B', 'C', 'DQA1', 'DQB1', 'DRB1'],
                           output_prefix='/data100t1/home/wanying/BioVU/20260305_AGD_250k_HLA_typing/output/AGD250k.kourami.imgt_v3.24_test')

In [ ]:
%%bash
# Run the code in terminal to combine files
python /data100t1/home/wanying/BioVU/20260305_AGD_250k_HLA_typing/code/utils/combine_kourami_results.py \
            "/DC3/AGD250k_HLA_typing/individual_hla_results/kourami_run_3.24" \
            "A,B,C,DQA1,DQB1,DRB1,DPB1" \
            "/data100t1/home/wanying/BioVU/20260305_AGD_250k_HLA_typing/output/kourami_result_combined_agd250k/AGD250k.kourami.imgt_v3.24"


# 3.59 and 3.64 only have default HLA genes
python /data100t1/home/wanying/BioVU/20260305_AGD_250k_HLA_typing/code/utils/combine_kourami_results.py \
            "/DC3/AGD250k_HLA_typing/individual_hla_results/kourami_run_3.59" \
            "A,B,C,DQA1,DQB1,DRB1" \
            "/data100t1/home/wanying/BioVU/20260305_AGD_250k_HLA_typing/output/kourami_result_combined_agd250k/imgt_v3.59/AGD250k.kourami.imgt_v3.59"

python /data100t1/home/wanying/BioVU/20260305_AGD_250k_HLA_typing/code/utils/combine_kourami_results.py \
            "/DC3/AGD250k_HLA_typing/individual_hla_results/kourami_run_3.64" \
            "A,B,C,DQA1,DQB1,DRB1" \
            "/data100t1/home/wanying/BioVU/20260305_AGD_250k_HLA_typing/output/kourami_result_combined_agd250k/imgt_v3.64/AGD250k.kourami.imgt_v3.64"

# 2. Check fialed ones

In [2]:
fn_failed = '/data100t1/home/wanying/BioVU/20260305_AGD_250k_HLA_typing/output/kourami_result_combined_agd250k/AGD250k.kourami.imgt_v3.24.invalid_samples.txt'
df_failed = pd.read_csv(fn_failed, sep='\t')
df_failed

,sample_id,result_file,reason
0,R240834150,/DC3/AGD250k_HLA_typing/individual_hla_results...,invalid_input
1,R207976296,/DC3/AGD250k_HLA_typing/individual_hla_results...,invalid_input
2,R231863041,/DC3/AGD250k_HLA_typing/individual_hla_results...,invalid_input
3,R275749017,/DC3/AGD250k_HLA_typing/individual_hla_results...,invalid_input
4,R204330508,/DC3/AGD250k_HLA_typing/individual_hla_results...,invalid_input
5,R293951636,/DC3/AGD250k_HLA_typing/individual_hla_results...,invalid_input
6,R263193874,/DC3/AGD250k_HLA_typing/individual_hla_results...,invalid_input
7,R276143441,/DC3/AGD250k_HLA_typing/individual_hla_results...,invalid_input
8,R222145706,/DC3/AGD250k_HLA_typing/individual_hla_results...,invalid_input
9,R214184834,/DC3/AGD250k_HLA_typing/individual_hla_results...,invalid_input
10,R295327885,/DC3/AGD250k_HLA_typing/individual_hla_results...,invalid_input
11,R203012760,/DC3/AGD250k_HLA_typing/individual_hla_results...,invalid_input
12,R235691300,/DC3/AGD250k_HLA_typing/individual_hla_results...,invalid_input
13,R291778281,/DC3/AGD250k_HLA_typing/individual_hla_results...,invalid_input
14,R260145411,/DC3/AGD250k_HLA_typing/individual_hla_results...,invalid_input
15,R208614430,/DC3/AGD250k_HLA_typing/individual_hla_results...,invalid_input
16,R228335617,/DC3/AGD250k_HLA_typing/individual_hla_results...,invalid_input
17,R227351976,/DC3/AGD250k_HLA_typing/individual_hla_results...,invalid_input
18,R263137409,/DC3/AGD250k_HLA_typing/individual_hla_results...,invalid_input
19,R239528734,/DC3/AGD250k_HLA_typing/individual_hla_results...,invalid_input
20,R200861095,/DC3/AGD250k_HLA_typing/individual_hla_results...,invalid_input
21,R235750592,/DC3/AGD250k_HLA_typing/individual_hla_results...,invalid_input
22,R282818454,/DC3/AGD250k_HLA_typing/individual_hla_results...,unable_to_split
23,R201836745,/DC3/AGD250k_HLA_typing/individual_hla_results...,invalid_input
24,R258361806,/DC3/AGD250k_HLA_typing/individual_hla_results...,invalid_input
25,R208701392,/DC3/AGD250k_HLA_typing/individual_hla_results...,invalid_input
26,R286637932,/DC3/AGD250k_HLA_typing/individual_hla_results...,invalid_input
27,R277583288,/DC3/AGD250k_HLA_typing/individual_hla_results...,invalid_input
28,R224631991,/DC3/AGD250k_HLA_typing/individual_hla_results...,invalid_input
29,R203491291,/DC3/AGD250k_HLA_typing/individual_hla_results...,invalid_input
30,R287633384,/DC3/AGD250k_HLA_typing/individual_hla_results...,invalid_input
31,R290146603,/DC3/AGD250k_HLA_typing/individual_hla_results...,invalid_input

In [5]:
print(df_failed['result_file'].iloc[22])

fn_unable_to_split = df_failed['result_file'].iloc[22]
df_unable_to_split = pd.read_csv(fn_unable_to_split, sep='\t', header=None)
df_unable_to_split

/DC3/AGD250k_HLA_typing/individual_hla_results/kourami_run_3.24/R282818454/R282818454_out.result

,0,1,2,3,4,5,6,7
0,A*02:01:01G,546.000000,1.000000,546,546.0,27.0,14.0,13.0
1,A*02:01:01G,546.000000,1.000000,546,546.0,27.0,14.0,13.0
2,B*39:01:01G,546.000000,1.000000,546,546.0,19.0,4.0,9.0
3,B*40:02:01G,546.000000,1.000000,546,546.0,19.0,4.0,9.0
4,C*01:02:01G,546.000000,1.000000,546,546.0,11.0,6.0,4.0
5,C*03:37:02,540.000000,0.989011,546,546.0,11.0,6.0,4.0
6,DQA1*05:01:01G,246.000000,1.000000,246,246.0,30.0,13.0,14.0
7,DQA1*04:01:01G,246.000000,1.000000,246,246.0,30.0,13.0,14.0
8,DQB1*03:01:01G,270.000000,1.000000,270,270.0,19.0,10.0,9.0
9,DQB1*04:02:01G,270.000000,1.000000,270,270.0,19.0,10.0,9.0
10,DRB1*08:02:01,270.000000,1.000000,270,270.0,30.0,15.0,9.0
11,DRB1*16:02:01G,270.000000,1.000000,270,270.0,30.0,15.0,9.0
12,DOA*01:01:02:03,249.000000,1.000000,249,249.0,25.0,13.0,12.0
13,DOA*01:01:02:03,249.000000,1.000000,249,249.0,25.0,13.0,12.0
14,DMA*01:01:01:02,285.000000,1.000000,285,285.0,33.0,17.0,16.0
15,DMA*01:01:01:02,285.000000,1.000000,285,285.0,33.0,17.0,16.0
16,DMB*01:02,282.000000,1.000000,282,282.0,33.0,17.0,16.0
17,DMB*01:02,282.000000,1.000000,282,282.0,33.0,17.0,16.0
18,DPA1*01:03:01G,246.000000,1.000000,246,246.0,17.0,9.0,8.0
19,DPA1*01:03:01G,246.000000,1.000000,246,246.0,17.0,9.0,8.0
20,DRA*01:01:02,246.000000,1.000000,246,246.0,33.0,17.0,16.0
21,DRA*01:01:02,246.000000,1.000000,246,246.0,33.0,17.0,16.0
22,DRB5*02:02:01G,270.000000,1.000000,270,270.0,8.0,4.0,4.0
23,DRB5*02:02:01G,270.000000,1.000000,270,270.0,8.0,4.0,4.0
24,F*01:01:01:07,546.000000,1.000000,546,546.0,12.0,6.0,6.0
25,F*01:01:01:07;F*01:01:01:06;F*01:01:01:05;F*01...,545.000000,0.998168,546,546.0,12.0,6.0,6.0
26,G*01:01:01:06,546.000000,1.000000,546,546.0,19.0,10.0,9.0
27,G*01:01:01:06,546.000000,1.000000,546,546.0,19.0,10.0,9.0
28,H*01:01:01:03,546.000000,1.000000,546,546.0,13.0,7.0,6.0
29,H*01:01:01:03,546.000000,1.000000,546,546.0,13.0,7.0,6.0
30,J*02:01;J*01:01:01:05;J*01:01:01:04;J*01:01:01...,545.000000,0.998168,545,546.0,25.0,13.0,12.0
31,J*02:01;J*01:01:01:05;J*01:01:01:04;J*01:01:01...,545.000000,0.998168,545,546.0,25.0,13.0,12.0
32,L*01:02,543.000000,0.998162,544,544.0,24.0,12.0,12.0
33,L*01:02,543.000000,0.998162,544,544.0,24.0,12.0,12.0
34,543,0.998162,544.000000,544,24.0,12.0,12.0,NaN
35,L*01:02,543.000000,0.998162,544,544.0,24.0,12.0,12.0